### ISSUE TITLE
Why is this repo untouched for 3 years?

### ISSUE THREAD

**Issue by greacen** [CDTProcurement/adpq#5]
Why is this repo untouched for 3 years? Kinda seems like this would be used more frequently. How does 
ADPQ fit into the CA IT world? How does it fit into the CWDS world?

**Comment by DebChu** [comment]
Hi Chris,

Yes, it's been a long time.  This repository is used to provide information about the refresh opportunities for PQVP (formerly ADPQ).  PQVP is still technically active but hasn't been refreshed since 2018. 

CDT is looking to refresh PQVP in early- to mid-2021 and expand it to include additional classifications and categories for agile development services.  A survey has been sent out to obtain feedback from the vendor community about which classifications and categories will best benefit State Agencies/Departments.  Additionally, CDT is looking to hold small workshops with vendors to garner valuable input to help CDT shape PQVP for the future.

You are encouraged to respond to the short survey at your earliest convenience:  https://www.surveymonkey.com/r/ZJ6K6C6

Thank you in advance for your participation.  We look forward to your feedback.

**Comment by greacen** [comment]
Thanks for the update @DebChu  -  I received the survey and stopped by this repo on a trip down memory lane.
